### ISSUE TITLE
Find reference points using two perpendicular lines

### ISSUE THREAD

**Issue by Bir9** [bashir2/penguins_fll_2021#1]
Method that will tank turn, move forward for a defined amount then tank turn to face perpendicular line, goes forward until both color sensors see black.

**Comment by bashir2** [comment]
Thanks Adib for filing this. So the end result of this would be a function whose signature is something like this:
```def follow_line(tank, left_cs, right_cs, millies):```
where `tank` is a `DriveBase` and the next two parameters are the color sensors. `millies` is the distance between the robot and the first line after the robot stops on the second perpendicular line.

As part of this exercise, please also create a function to check if both sensors are on black.

**Comment by bashir2** [comment]
Thanks Adib, let's not use threading for now (Python and threads do not play well for technical reasons). I don't see why you need parallel functions though. You can turn on the driving motors (and not stop them); then keep checking color sensors until they are both on block, right?
